blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.product_list, name='product-home'),
    path('s/', views.search, name='search'),
    path('', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

djp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from cart import views as cart_views
from orders import views as order_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    re_path(r'^plus_one_cart/(?P<id>\d+)/$', cart_views.increase_by_one, name='increase_by_one'),
    re_path(r'^minus_one_cart/(?P<id>\d+)/$', cart_views.decrease_by_one, name='decrease_by_one'),
    re_path(r'^cart/(?P<id>\d+)/$', cart_views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^cart/(?P<slug>[\w-]+)/$', cart_views.add_to_cart, name='add_to_cart'),
    re_path(r'^address_form/(?P<id>\d+)/$', user_views.edit_address, name='edit_address'),
    re_path(r'^remove_address/(?P<id>\d+)/$', user_views.remove_address, name='remove_address'),
    path('cart/', cart_views.cart_home, name='cart'),
    path('address_form/', user_views.new_address, name='new_address'),
    path('checkout/', order_views.checkout, name='checkout'),
    path('orders/', order_views.orders, name='orders'),
    path('', include('blog.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<slug:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    slug = models.SlugField(max_length=150)
    stock = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products', blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:product_detail', args=[self.id, self.slug])


class VariationsManager(models.Manager):
    def all(self):
        return super(VariationsManager,self).filter(active=True)

    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')


VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, related_name="variations", on_delete=models.CASCADE)
    category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
    title = models.CharField(max_length=120)
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0.00, blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    objects = VariationsManager()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def search(request):
    try:
        q = request.GET.get('q')
    except:
        q = None
    if q:
        products = Product.objects.filter(name__icontains=q)
        context = {'query': q, 'products': products}
    else:
        context = {}
    return render(request, 'blog/result.html', context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'blog/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {
        'product': product
    }
    return render(request, 'blog/details.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <script src="https://kit.fontawesome.com/ec3df03138.js" crossorigin="anonymous"></script>
    {% if title %}
        <title> WEBSITE {{ title }} </title>
    {% else %}
         <title> WEBSITE </title>
    {% endif %}

    <style>
        .product-img-div {
            height:400px;
        }
        .product-img {
            width:100%;
            height:100%;
        }


        .card-signin {
  border: 0;
  border-radius: 1rem;
  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
}

.card-signin .card-title {
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 1.5rem;
}

.card-signin .card-body {
  padding: 2rem;
}

.form-signin {
  width: 100%;
}

.form-signin .btn {
  font-size: 80%;
  border-radius: 5rem;
  letter-spacing: .1rem;
  font-weight: bold;
  padding: 1rem;
  transition: all 0.2s;
}

.form-label-group {
  position: relative;
  margin-bottom: 1rem;
}

.form-label-group input {
  height: auto;
  border-radius: 2rem;
}

.form-label-group>input,
.form-label-group>label {
  padding: var(--input-padding-y) var(--input-padding-x);
}

.form-label-group>label {
  position: absolute;
  top: 0;
  left: 0;
  display: block;
  width: 100%;
  margin-bottom: 0;
  /* Override default `<label>` margin */
  line-height: 1.5;
  color: #495057;
  border: 1px solid transparent;
  border-radius: .25rem;
  transition: all .1s ease-in-out;
}

.form-label-group input::-webkit-input-placeholder {
  color: transparent;
}

.form-label-group input:-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-moz-placeholder {
  color: transparent;
}

.form-label-group input::placeholder {
  color: transparent;
}

.form-label-group input:not(:placeholder-shown) {
  padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
  padding-bottom: calc(var(--input-padding-y) / 3);
}

.form-label-group input:not(:placeholder-shown)~label {
  padding-top: calc(var(--input-padding-y) / 3);
  padding-bottom: calc(var(--input-padding-y) / 3);
  font-size: 12px;
  color: #777;
}

.btn-google {
  color: white;
  background-color: #ea4335;
}

@media screen and (max-width: 768px) {
            .product-img-div {
                height: 320px;
            }
        }
        @media (max-width: 840px){
        .container {
            max-width: 530px;
        }
        @media (max-width: 640px){
        .container {
            max-width: 300px;
        }
        @media (max-width: 420px){
        .container {
            max-width: 200px;
        }
    </style>

</head>
<body style="margin-top: 0; background: #fff">
        <header class="site-header">
          <header style="background-color:#616D7E">
          <nav class="navbar navbar-expand-lg navbar-light "style="background:transparent;">
           <img src="https://www.iitg.ac.in/stud/gymkhana/technical/assets/img/resources/codingclubLogo.png" width="60" height="60" alt="">
            <div class="container">
              <a style="color: #FFFFFF" class="navbar-brand mr-4" href="{% url 'blog:product-home' %}">WEBSITE </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'polls:index' %}">Polling</a>
                </div>

              <form class="form-inline my-2 my-lg-0" action='/s/'>
                  <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search" >
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        {% if user.profile.is_merchant == 1 %}
                            <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'admin:index' %}">Manage Products</a>

                        {% endif %}
                             <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>

                        <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'"class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                <a style="color: #FFFFFF" onMouseOver="this.style.color='#3090C7'" onMouseOut="this.style.color='#FFFFFF'" class="nav-item nav-link" href="{% url 'cart' %}">Cart  <span class="badge">{{ request.session.items_total }}</span></a>
                </div>
              </div>
            </div>
          </nav>
         </header>
        <hr style="width: 90%;background:linear-gradient(to right,deeppink,dodgerblue);height: 3px">



    </header>


            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {%  endfor %}
            {% endif %}
            {% block content %}
            {%  endblock %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
</body>
</html>

blog/templates/blog/details.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <br>
    <br>
    <div class="row">
    <div class= "col-md-2"></div>
    <div class="col-md-8">
   <div class="card mb-3" style="width: 60rem;background: transparent; border: none">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img class="rounded" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt="..." style="width: 100%; height: auto">
            </div>
            <div class="col-md-8" style="padding-left: 20px">
                <div class="card-body">
                    <h3>{{ product.name }}</h3>
                    <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                    <p class="text-muted"> {{ product.price }} Rupees</p>
                    <p>{{ product.description|safe|linebreaksbr }}</p>
                    <form class="form pull-right" method='POST' action='{% url 'add_to_cart' product.slug %}'>{% csrf_token %}
                        <input class="form-control" name="qty" type='number' value="1" min="1" >
                            <br>
                        {% if product.variations.all %}
                            {% if product.variations.sizes %}
                                <select name="size" class="form-control">
                                    {% for item in product.variations.sizes %}
                                        <option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>

                                    {% endfor %}

                                </select>
                                <br>
                                {% endif %}
                                {% if product.variations.colors %}
                                    <select name="color" class="form-control">
                                    {% for item in product.variations.colors %}
                                        <option value="{{ item.title|lower }}">{{ item.title|capfirst }}<br></option>

                                    {% endfor %}

                                </select>
                                    <br>
                                {% endif %}
                            {%  endif %}
                                <input type="submit" value="Add to Cart">
                            </form>

                </div>
            </div>
        </div>
   </div>
   </div>
    </div>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}
    <h1> Home!</h1>
{% endblock content %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
{% comment %}<div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt="..." style="width: 100%; height: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">{{ product.price }} Rupees</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
        <div class="col-md-2"></div>
        <div class="col-md-2 col-md-offset-4 blog-sidebar ">
          <div class="sidebar-module">
            <h4 style="text-align:center;">Categories</h4>
            <ol class="list-unstyled text-center">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'blog:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->{% endcomment %}
    <br>
              <br>
<div class="container" style="margin-left: 2%; margin-right: 2%; max-width: 95%">
    <div class="row">

               <div  class="col-lg-2" style="margin-bottom: auto">

            <h4 style="text-align:center;" >Categories</h4>

            <ul style="list-style-type:none;" class="list-group text-center">
              <li style="background: transparent; margin-bottom: 0.4rem" {% if not category %} class="list-group-item mb-2"{% endif %}><a  href="{% url 'blog:product_list' %}">All</a></li>

            {% for c in categories %}

              <li style="background: transparent; margin-bottom: 0.4rem" {% if category.slug == c.slug %} class="list-group-item mb-2"{% endif %}>

                  <a  href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ul>
 <br>

        <br>
               </div>


    <div class="col-lg-10">
              <div class="row" style="margin-left: 0;margin-right: 0">


                  {% for product in products %}
                      <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6 mb-4">

                              <div class="card" style="height: 100%">
                                 <a href="{{ product.get_absolute_url }}">
                                 <div class="img-hover-zoom">
                                     <div class="product-img-div">
                                   <img class="product-img" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt="..." >
                                         </div>
                                 </div>

                                 </a>
                                <div class="card-body">
                                  <h5 class="card-title" style="align-content: center" > <a style="color: #ff1493" href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
{#                                   <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>#}
                                    <h5 class="card-title"> {{ product.price }} Rupees</h5>
                                </div>
                              </div>

                      <br>
                      </div>
                  {% endfor %}
              </div>

</div>
    </div>
    </div>
{% endblock content %}

blog/templates/blog/result.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.png' %} {% endif %}" alt="..." style="width: 100%; height: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">{{ product.price }} Rupees</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
        <div class="col-md-2"></div>


      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock content %}